# docker-compose.prod.yml - THE FINAL & MOST ROBUST VERSION

version: '3.8'

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports: ["80:80", "443:443"]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on: [frontend, backend]
    # FIX: Load all variables directly from the .env file.
    env_file: ./.env

  frontend:
    build:
      context: ./frontend
      # FIX: Pass the build argument directly from the .env file.
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    restart: unless-stopped
    expose: [3000]
    # FIX: Load all variables directly from the .env file.
    env_file: ./.env

  backend:
    build: ./backend
    restart: unless-stopped
    expose: [3001]
    # FIX: Load all variables directly from the .env file.
    env_file: ./.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: timescale/timescaledb:latest-pg16
    restart: unless-stopped
    # FIX: Load all variables directly from the .env file.
    env_file: ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  caddy_data:
  caddy_config:
  db_data: